/*
 * mbr_makever.cpp
 * Program that creates mbr_version.cpp
 *
 * Created by Jayanth Chennamangalam
 */

#include <iostream>
#include <time.h>

#include "mbr_common.h"

#define MBR_PATH_VER            "version"
#define MBR_FILE_VERSRC         "mbr_version.cpp"
#define MBR_VAR_VER             "*g_pcVersion"
#define MBR_VER_BUILD_DELIM     "-"

/*
 * main()
 *
 * The main function
 */
int main(int argc, char *argv[])
{
    fstream VerFile;
    fstream VerSrcFile;
    time_t Time;
    struct tm *pstTime = NULL;
    char acVersion[MBR_MAX_LEN_GENSTRING] = {0};
    char acBuild[MBR_MAX_LEN_GENSTRING] = {0};

    /* read the text file MBR_PATH_VER to get the version info */
    VerFile.open(MBR_PATH_VER, fstream::in);
    VerFile.getline(acVersion, MBR_MAX_LEN_GENSTRING);
    VerFile.close();

    /* get the build info */
    Time = time(NULL);
    pstTime = localtime(&Time);
    (void) strftime(acBuild, sizeof(acVersion), "%Y%m%d-%H%M%S", pstTime);

    /* append the build info to the version info */
    (void) strncat(acVersion, MBR_VER_BUILD_DELIM, MBR_MAX_LEN_GENSTRING);
    (void) strncat(acVersion, acBuild, MBR_MAX_LEN_GENSTRING);

    /* open the version source file for writing */
    VerSrcFile.open(MBR_FILE_VERSRC, fstream::out);

    /* write header comments */
    VerSrcFile << "/*" << endl
               << " * " << MBR_FILE_VERSRC << endl
               << " * " << "The MBR version file" << endl
               << " * " << endl
               << " * " << "Generated by the mbrmakever program - DO NOT MODIFY"
               << endl
               << " */" << endl;
    VerSrcFile << endl;

    /* write the global variable definition */
    VerSrcFile << "const char " << MBR_VAR_VER
               << " = \"" << acVersion << "\";" << endl;
    VerSrcFile << endl;

    VerSrcFile.close();

    return MBR_RET_SUCCESS;
}

