#!/bin/bash

# init
#echo "Initialising..."
#sysctl -w vm.dirty_expire_centisecs=500

# run the acquisition programs
echo "Running the acquisition programs..."
taskset 0x00000001 ~/src/acquire/acquire_pcap_shm eth0 > wr_shm_acq_0 &
sleep 1
taskset 0x00000002 ~/src/acquire/acq_write2file > wr_shm_hd_0

# check for slips in the output
echo "Checking for slips in the output. Number of slips:"
sleep 10
grep "Slip" wr_shm_acq_0 | wc -l

# check for slips in the data file
echo "Checking for slips in the data file. Number of slips:"
~/src/acquire/long_mark_gap packet 4 20 10 > wr_shm_check_0
grep "Slip" wr_shm_check_0 | wc -l

# diff for inconsistencies
echo "Inconsistencies:"
diff wr_shm_acq_0 wr_shm_check_0 | grep "Slip"

echo "DONE"

